final List<Map<String, dynamic>> popularProducts = [
  {
    'id': '10',
    'imagePath': 'assets/images/card1.png',
    'title': 'Orange (South Africa)',
    'weight': '2kg',
    'price': 245.0,
    'buttonText': 'Add to cart',
  },
  {
    'id': '12',
    'imagePath': 'assets/images/card2.png',
    'title': 'Gulsha Tengra',
    'weight': '1kg',
    'price': 450.0,
    'buttonText': 'Add to cart',
  },
  {
    'id': '13',
    'imagePath': 'assets/images/card3.png',
    'title': 'Product 2',
    'weight': '100kg',
    'price': 200.0,
    'buttonText': 'Add to cart',
  },
  {
    'id': '14',
    'imagePath': 'assets/images/card4.png',
    'title': 'Product 3',
    'weight': '100kg',
    'price': 200.0,
    'buttonText': 'Add to cart',
  },
  {
    'id': '15',
    'imagePath': 'assets/images/card5.png',
    'title': 'Nestle asd asdkjsd sdasdksd sdasd',
    'weight': '100kg',
    'price': 200.0,
    'buttonText': 'Add to cart'
  },
  {
    'id': '16',
    'imagePath': 'assets/images/card6.png',
    'title': 'Nestle asd asdkjsd sdasdksd sdasd',
    'weight': '100kg',
    'price': 200.0,
    'buttonText': 'Add to cart',
  },
  {
    'id': '17',
    'imagePath': 'assets/images/card7.png',
    'title': 'Nestle asd asdkjsd sdasdksd sdasd',
    'weight': '100kg',
    'price': 200.0,
    'buttonText': 'Add to cart',
  },
  {
    'id': '18',
    'imagePath': 'assets/images/card8.png',
    'title': 'Nestle asd asdkjsd sdasdksd sdasd',
    'weight': '100kg',
    'price': 200.0,
    'buttonText': 'Add to cart',
  },
];